### PR TITLE
Initial routing info

### PR DESCRIPTION
**Pull request by Mer-lone**
This is for updating the routing info for the projects.

### CODE REVIEW

**Comment by Phil-Barv** [comment]
Nice! My only concern is that cause we're using React Frontend, instead of routing to templates, all our routes will just essentially be queries, and in the frontend, we'll fetch the data from the backend using: fecth("api/") as was shown in the index() route. So not sure these would work as is.

**Comment by pabloguarneros** [comment]
Hi! Nice observation. Rather than creating routes to the app, we can use states for the app that change when we click on different buttons.

**Comment by Mer-lone** [comment]
I think this works fine. Try working with it first.

**Comment by pabloguarneros** [comment]
@Mer-lone Your query approach works for me! My rather than create routes to the app was about the front-end.

**Comment by Phil-Barv** [comment]
Yup yup, queries are fine cause we'd just be querying the models and as Pablo said, use states to hook the data.

**Comment by Humancyyborg** [comment]
> Hi! Nice observation. Rather than creating routes to the app, we can use states for the app that change when we click on different buttons.

Since you are working on the front end, you can provide her with an example of  how you want the route to be exposed..I think something like this is better demonstrated  with an example

**Comment by pabloguarneros** [comment]
@Humancyyborg Thanks for the heads up.
@Mer-lone, sorry for not giving an example.

For the front-end, I was imagining something like this: we have "state" as a variable that we update with setState(#). When a user presses a button, the react component would reload and change to either project browser, your donations, or edit profile depending on the value of the state.

```javascript
const [state, setState] = useState(1); // set state to a default value of 1

  const renderView = () => {
    switch(state){ // think of this as if / elif from python
      case 1: // if state == 1
        return <ProjectBrowser />
      case 2: // elif state == 2
        return <YourDonations/>
      case 3: // elif state == 3
        return<EditProfile />

    }
  }

  return (
      <Button onClick={setState(1)} /> 
      <Button onClick={setState(2)} />
      <Button onClick={setState(3} /> 
)
 
```

**Comment by pabloguarneros** [comment]
I overlooked @Phil-Barv 's previous concern. I think his observation was really important. For routing, is there a way to send a response rather than redirect a user to a template?

We are currently returning.
```python
return f" sorry project  with id = {id} Does not exist"
# or 
return render_template('update.html', project = project) would need to send a response 
```
Could we return?

```python
return {"response" : f"sorry project  with id = {id} Does not exist"}
# or 
return {"response" : project}
```
We would have to convert the project object into a dictionary that we can pass into a json response.

A benefit of only returning responses is that we could leave the routing to the frontend and the CRUD changes to the backend.

**Comment by Phil-Barv** [comment]
@pabloguarneros in my thinking, we would need to run the query in the backend, then send a jsonified data packet to the frontend, where it's unpacked and displayed within the relevant component. The frontend code would be similar to what you wrote above (yesterday).

**Comment by Humancyyborg** [comment]
> @pabloguarneros in my thinking, we would need to run the query in the backend, then send a jsonified data packet to the frontend, where it's unpacked and displayed within the relevant component. The frontend code would be similar to what you wrote above (yesterday).

my roommate recommended using Axios to accomplish something like, @Mer-lone  will see if I can find any resources that would help

**Comment by Mer-lone** [comment]
Thanks  @Humancyyborg <https://github.com/Humancyyborg>

**Pull request merged**
