### PR TITLE
Charity add edit project

### PR DESCRIPTION
**Pull request by cyrushhc**
1. Created the BrowseProject page for the Charity. Added a button to allow charity to add project. 
2. Changed the ProjectPage so that it display different state for different types of users (charity vs donor).
3. In the ProjectPage, Allowed charity to update the information about their project. To do this, I changed the updateProject function on route.py and added a function on the api.js 
5. In the ProjectPage, Allowed charity to delete the project. To do this, I changed the updateProject function on route.py and added a function on the api.js

### CODE REVIEW

**Comment by pabloguarneros** [comment]
Hi Cyrus, 

I liked how you made it easy to edit the project. I also liked that when you click on the edit page you get the current project name and description. I am wondering whether it should be as easy to delete a project? We might talk to the users about this, but it feels that if they accidentally press a button, we might lose valuable information they might get angry with. 

For the implementation on
```python
@app.route('/project/<int:id>/update',methods = ['GET','POST'])
def updateProject(id):
```
it seems we are deleting the project and committing the delete to the database. 
```python
db.session.delete(project)
db.session.commit()
```
What happens if the user's new title or description is invalid (for example, they go over the character limit in our database or have invalid characters?). It seems that the project would get deleted and we wouldn't be able to create a new project given invalid entries.

```python
db.session.delete(project)
db.session.commit()
title = request.json['title']
description = request.json['description']
project = Project(
                title = title,
                description = description)
db.session.add(project)
db.session.commit()
```

Is there a way to put both the delete and the addition of the project in a single transaction before committing to the database?

Also, is deleting the best method to update the project? What happens if something is pointing to the project's unique ID (for example a user comment, a user transaction, or a project subgoal)? When we delete and add a new project, would we have to change the IDs of all of these pointers?

For example, if we create a table 
```class DonorProject(db.Model):
id = db.Column(db.Integer, primary_key=True, autoincrement=True)
donor_id = db.Column(db.Integer, db.ForeignKey("donor.id")
project_id = db.Column(db.Integer, db.ForeignKey("project.id")
```
Would the project_id entry have to change whenever a charity updates the project?

**Comment by Phil-Barv** [comment]
@pabloguarneros  raises some very valid concerns. We need to maintain referential integrity after deletion. Not sure what's the best way to go about it but I have three suggestions you can test:

1. Add a "are you sure you want to permanently delete this?" alert for the user.
2. This might involve restructures in the backend: not actually delete the item but just prevent its render to the user. (ethical concerns maybe?)
3. With SQLAlchemy referential integrity is maintained so deleting an item with a relationship with another item, updates all the tables, so option 3 is to investigate if anything else breaks once you delete if it doesn't, leave it as is.

In response to the character limits, we have set them in the DB models, so here we can either:

1. As is, if the user tries to enter the characters above, it should fail to commit changes and would refresh the page on them, so maybe find a way to persist what they had already typed.
2. Flash an error when the character limit is over. This would involve setting parameters on the form input boxes. I'm sure there's a way to do that.

Great work, @cyrushhc !

**Comment by cyrushhc** [comment]
Thanks for the feedback @pabloguarneros and @Phil-Barv. 

1. I changed the delete to update 
2. Added a delete confirmation message.

**Comment by pabloguarneros** [comment]
@cyrushhc  Is there a reason for having two backend folders?

**Pull request closed without merging**
