### PR TITLE
formatted essential login, signup & create modals

### PR DESCRIPTION
**Pull request by Phil-Barv**
This PR fixes formatting issues for better UI/UX design in the following places (Donor + Charity):

1. Login Page
2. Sign Up Page
3. Project Card 
4. Create a new project modal
5. Button Behavior (on-hover)

### CODE REVIEW

**Review by pabloguarneros — CHANGES_REQUESTED** [review]
Nice work on getting the updates through. The app looks great.

Why did you choose to create the buttons and styling over using the MUI library and the button styles that already exist? Seems great though. We can work on creating one style later.

I've seen that you changed the variable name from "donor" to "Donor." This seems like a minor change, but is there a particular reason for the change? When we create other variables, should we opt for uppercase or lowercase if there's only one word?

My only suggestion would be to keep variable names with camelcase. So if there's one word, it should be lowercase. However, if you have a valid reason for doing it uppercase, I'm on board.

**Comment by Phil-Barv** [comment]
@pabloguarneros I opted to create my own styling as there was an issue with how to target specific tags, and therefore I had to set styling for the entire class. For example, instead of just targeting the <input> in the login form, I targetted all the <input>s. This made changes to the buttons look funky, therefore my decision to create custom styling. I'm open to updating it if you have any good resources at hand!

The change of the variable name was purely for aesthetic purposes on render! The lower cases affected the design of the title when on the login page: 'Registering as a donor' and now it renders: 'Registering as a Donor'

**Review by pabloguarneros — APPROVED** [review]
Okay, yes! With your help, I realized it wasn't the variable name but the string you are passing through that got capitalized. This makes sense. Looks good then!

**Comment by Phil-Barv** [comment]
@pabloguarneros 
Since I posted the PR, I have made commits that have addressed:

1. Refactoring the render views
2. Editing header metadata 
3. Adding app icon
4. Updating forms to distinguish donor username and charity orgname
5. Implemented grid view for BrowseProjects (for charity  + donor)

We should move to merge this PR soon (after you finish with the Login/Signup forms issue) as the drift from the main is getting bigger. 

Update: Implemented grid view for Your Donations page.

**Pull request merged**
