### PR TITLE
creating Auth & updating  db models

### PR DESCRIPTION
**Pull request by Humancyyborg**
---Updated db model based on cyrus recommndation
---Login for donors and charity
---modifying backend file structure

Screen Shot 2022-03-26 at 6 30 40 PM

### CODE REVIEW

**Comment by Phil-Barv** [comment]
Hey, looking good! Just some minor comments... 
1. For validation, look into flask_login, it's a much cleaner implementation of user authentication as it offers UserMixin, login_user, LoginManager, login_required, logout_user, current_user e.t.c.
2. A single models.py file is adequate, no need to create files for each model.
3. In the Donor model, please add the FirstName field, as we would expect the donor to sign up with a FirstName, LastName (for security reasons as we're dealing with money and would require to know both their names). The username can just be their last name by default.
4. I think we only need a single LogInForm rather than a separate one for the donor, and the charity as regardless of your User status, you would only need to log in with your username and password.

**Comment by pabloguarneros** [comment]
What is the expected behavior for the forms file and would we query that with the routes implementation @Mer-lone ?

**Comment by Humancyyborg** [comment]
> What is the expected behavior for the forms file and would we query that with the routes implementation @Mer-lone ?

First, I will be rewriting the auth implementation,  I initially tried to build on  the code sent by Philip, but would have to handle it in a more standard way

"What is the expected behavior for the forms file", don't understand this question, " would we query that with the routes ", I have not added the routes yet, yes, you will need the route..something like this without(...

#routing for authentication
@main.route('/login', methods=["GET", "POST"])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
      #change this to donor
        user = User.query.filter_by(email=form.email.data).first()
      #chnage this to donor
        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            redirect_url = request.args.get('next') or url_for('main.login')
            return redirect(redirect_url)
    return render_template('login.html', form=form)


@main.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

**Comment by Phil-Barv** [comment]
This looks good @Humancyyborg. 

@pabloguarneros because the forms are classes, we would just create an instance as illustrated by Daniel. 

Just to iterate, with flask_login no validation is required just the "@login_required" decorator above the route function. It also reduces queries to the backend for the current user because you can use the "current_user" functionality that flask_login comes with. (This does not apply to this example as you do NOT need to be logged in to log in, lol!)

This is Daniel's example, just edited some places and fixed indentation and showed a possible password protection solution using flask_bycrypt for encryption, flash to display messages to the frontend (display can be made cleaner using JS in the frontend to customize beyond the plain alert boxes) and flask_login's "login_user". Also, the example would need to be updated to use the states suggested by Pablo: 

```python
#login user
@app.route("/login/", methods=["POST", "GET"])
def login():

    #note: no parameters are passed into the form
    form = LoginForm()

    if form.validate_on_submit():
        #we can create a join table called users containing all charities and donors
        user = Users.query.filter_by(email=form.email.data).first() 

        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('home'))
            else:
                flash(f"Oops, you put the wrong password, {form.email.data}. Try again.", "info") 
        else:
            flash(f"{form.email.data}, please create an account!", "info")
    
    return render_template("login.html", form=form)

```

**Comment by pabloguarneros** [comment]
@Phil-Barv and @Humancyyborg thanks for the example. Your example helped clarify the approach we should be taking. @Humancyyborg, sorry about the lack of clarity in my question. I was asking about how the form classes would get implemented. Both of you were able to answer the question, so thanks for thinking ahead!

**Comment by pabloguarneros** [comment]
Is there a specific reason for attaching a donor's id to the Project model?

```python
class Project(db.Model):
  ...
  donor_id = db.Column(db.Integer, db.ForeignKey('donor.id'), nullable=False)
```

**Comment by Phil-Barv** [comment]
@pabloguarneros, it seems some comments have been deleted but the associated comment to this entry was: 

On the donor model

```python 
#donor user model 
class Donor(db.Model):
    ...
    #one to many relationship with projects -> displayed in "my projects"
    projects_list = db.relationship('Project', backref='donor_projects', lazy=True)

```

On the project model

```python 
class Project(db.Model):
  ...
  donor_id = db.Column(db.Integer, db.ForeignKey('donor.id'), nullable=False)
```

The thinking was that a donor would have the "my projects" page that is associated with either liking/donating to the project.

**Comment by Phil-Barv** [comment]
@Humancyyborg I've made some changes that have resolved the conflict of your PR with Master. Review them and give me the go-ahead to merge.

**Comment by Phil-Barv** [comment]
It seems this PR has gone stale and you are currently working on the 'Donation Table' PR. I will go ahead and close this one @Humancyyborg @Mer-lone @pabloguarneros

**Pull request closed without merging**
