### PR TITLE
Donation table

### PR DESCRIPTION
**Pull request by Humancyyborg**
#Table to track donations  from donors
#feel free to suggest  adding more attributes to the model
Screen Shot 2022-04-12 at 2 06 53 AM

### CODE REVIEW

**Comment by pabloguarneros** [comment]
We solved the conflicts between tables in a call between Daniel and I.
The conflicts we resolved were:
- Adding an autoincrement field in the primary key so that the id field gets updated automatically.
- Removing some typos in the Project table ("description" field's spelling and imageUrl changing it from camel case to snake case)
- Adding the jsonify function in the Project table.

@Mer-lone We are adding you as a reviewer. Could you verify whether this configuration works for you. Specifically, do you think the current models map the relationships one-to-one and many-to-one we would like to create between Donors and Projects?

**Comment by Phil-Barv** [comment]
@pabloguarneros @Humancyyborg  Not sure the autoincrement is necessary (Flask-SQLAlchemy automatically handles it). About the relationship, should it be many to many? A donor can have many projects and a project can have many donors? Let me know if I'm misunderstanding your comment.

**Comment by pabloguarneros** [comment]
@Phil-Barv I didn't know that SQL-Alchemy already handled it! Thanks for pointing it out. Many to many also makes sense. For now, I'm all set for this merge. Just waiting on @Mer-lone to have a final look.

**Comment by Phil-Barv** [comment]
@Mer-lone @pabloguarneros @Humancyyborg waiting on an update to finalize this PR.

**Pull request merged**
