### PR TITLE
Pruned duplicate files from main

### PR DESCRIPTION
**Pull request by Phil-Barv**
This PR is a maintenance of the main branch. Actions:

1. Deleted duplicate files
2. Deleted venv
3. Updated requirements.txt

### CODE REVIEW

**Comment by pabloguarneros** [comment]
It's looking good.

For now, when installing the dependencies, not all of the libraries have been added to the requirements.txt file. Additionally, when running with Python 3.6.8, we have "No matching distribution found for itsdangerous==2.1.2."

Here would be an update of the requirements.txt file

```
bcrypt==3.2.0
cffi==1.15.0
click==8.0.4
colorama==0.4.4
dnspython==2.2.1
email-validator==1.1.3
Flask==2.0.3
Flask-Bcrypt==1.0.1
Flask-Cors==3.0.10
Flask-JWT-Extended==4.3.1
Flask-SQLAlchemy==2.5.1
Flask-WTF==1.0.1
greenlet==1.1.2
gunicorn==20.1.0
idna==3.3
itsdangerous==2.1.2
Jinja2==3.1.0
MarkupSafe==2.1.1
pycparser==2.21
PyJWT==2.3.0
python-dotenv==0.20.0
six==1.16.0
SQLAlchemy==1.4.32
Werkzeug==2.0.3
WTForms==3.0.1
```

Within the frontend we still have another subdirectory called "aben's frontend," and I wanted to make sure with @abenezer-molla if there was anything from this directory he would like to keep.

Other files we might consider deleting would be "site.db", "todo.txt" and changing the .gitignore file currently under the frontend directory to the root directory.

But things look good for this PR and I can work on this

Other than that, things look good. If you want to merge without the edits, I could make those edits afterward too. Whatever works for you @Phil-Barv .

**Review by pabloguarneros — COMMENTED** [review]
It's looking good.

For now, when installing the dependencies, not all of the libraries have been added to the requirements.txt file. Additionally, when running with Python 3.6.8, we have "No matching distribution found for itsdangerous==2.1.2."

Here would be an update of the requirements.txt file

bcrypt==3.2.0
cffi==1.15.0
click==8.0.4
colorama==0.4.4
dnspython==2.2.1
email-validator==1.1.3
Flask==2.0.3
Flask-Bcrypt==1.0.1
Flask-Cors==3.0.10
Flask-JWT-Extended==4.3.1
Flask-SQLAlchemy==2.5.1
Flask-WTF==1.0.1
greenlet==1.1.2
gunicorn==20.1.0
idna==3.3
itsdangerous==2.1.2
Jinja2==3.1.0
MarkupSafe==2.1.1
pycparser==2.21
PyJWT==2.3.0
python-dotenv==0.20.0
six==1.16.0
SQLAlchemy==1.4.32
Werkzeug==2.0.3
WTForms==3.0.1
Within the frontend we still have another subdirectory called "aben's frontend," and I wanted to make sure with @abenezer-molla if there was anything from this directory he would like to keep.

Other files we might consider deleting would be "site.db", "todo.txt" and changing the .gitignore file currently under the frontend directory to the root directory.

But things look good for this PR and I can work on this

Other than that, things look good. If you want to merge without t

**Comment by pabloguarneros** [comment]
Looks great! @Phil-Barv

**Comment by Phil-Barv** [comment]
@pabloguarneros i've implemented the suggested changes. Take a look and let me know

**Pull request merged**
